[package]
name = "theotui"
version = "0.4.6"
license.workspace = true
edition.workspace = true
repository.workspace = true
description = "A TUI to explore theoretical computer science topics."

[dependencies]
theoinf = { path = "../theoinf", version = "0.4.5"}
ratatui = "0.30.1"
color-eyre = "0.6.5"
strum = "0.28.0"
ratatui-textarea = "0.9.1"
